version: '3'

services:
  go120:
    build:
      context: .
      dockerfile: DockerGo
    working_dir: '/root/'
    ports:
      - "9080:9080"
      - "80:80"
    tty: true
    volumes:
      - ../:/root/
    command: >
      bash -c "
      go get go.mongodb.org/mongo-driver/mongo &&
      pwd &&
      bash
      "

  nginx:
    build:
      context: .
      dockerfile: DockerNginx
    ports:
      - "443:443"
    tty: true
    depends_on:
      - "go120"
    volumes:
      - ../public:/usr/share/nginx/html
      - ./nginx_local.conf:/etc/nginx/conf.d/nginx_local.conf
      - ./server.crt:/etc/nginx/conf.d/server.crt
      - ./server.key:/etc/nginx/conf.d/server.key

  node:
    image: node:lts
    volumes:
      - ../vue:/app/vue
      - ../public/assets:/app/vue/dist/assets
      - ../view:/app/vue/dist/view
    working_dir: /app/vue
    tty: true
    ports:
      - 3000:3000

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 12345678
    ports:
      - 27017:27017
    volumes:
      - ./db/mongo/:/mongohost

