version: '3'

services:
  go120:
    build:
      context: .
      dockerfile: DockerGo
    working_dir: '/root/'
    env_file:
      - ../infrastructure/chat.env
    ports:
      - "9080:9080"
      - "80:80"
    tty: true
    volumes:
      - ../:/root/
    command: >
      bash -c "
      go get go.mongodb.org/mongo-driver/mongo &&
      pwd &&
      bash
      "

  nginx:
    build:
      context: .
      dockerfile: DockerNginx
    ports:
      - "443:443"
    tty: true
    depends_on:
      - "go120"
    volumes:
      - ../public:/usr/share/nginx/html
      - ./nginx_local.conf:/etc/nginx/conf.d/nginx_local.conf
      - ./server.crt:/etc/nginx/conf.d/server.crt
      - ./server.key:/etc/nginx/conf.d/server.key

  node:
    image: node:lts
    volumes:
      - ../vue:/app/vue
      - ../public/assets:/app/public/assets
      - ../view:/app/public/view
    tty: true
    ports:
      - 3000:3000

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 12345678
    ports:
      - 27017:27017
    volumes:
      - ./:/data/

  mongo-express: #basic auth : admin/pass
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: 12345678
      ME_CONFIG_MONGODB_URL: mongodb://root:12345678@mongo:27017/

  mongo-express-prod:
    # this cli run on local pc at first
    # ssh quigen -L 27017:127.0.0.1:27017
    # vi config.default.js
    # 8081 >> 8082
    image: mongo-express
    profiles: ["manual"]
    ports:
      - 8082:8082
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://host.docker.internal:27017/
      ME_CONFIG_BASICAUTH: "false"

  # redis:
  #   image: "redis:latest"
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - "./redis:/data"

